[theme]
primaryColor="#0047AB"  # Azul Cobalto
backgroundColor="#F4C2C2"  # Rosa Palo
secondaryBackgroundColor="#FFD700"  # Amarillo Pato
textColor="#2c3e50"  # Texto gris oscuro (neutro para buena visibilidad)
font="Sans serif"  # Fuente predeterminada
